// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0FHAC8dkni2iizrRrqoenjN5Z0fTE77g',
    appId: '1:603417356334:web:a1e5cb7c157e77b04397bf',
    messagingSenderId: '603417356334',
    projectId: 'prontomoto-d4547',
    authDomain: 'prontomoto-d4547.firebaseapp.com',
    storageBucket: 'prontomoto-d4547.firebasestorage.app',
    measurementId: 'G-DR4X665FMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIC_bycfhhgHqyx4wBh-HxeUAehqZqFiY',
    appId: '1:603417356334:android:b3bb1c38c8db1eb54397bf',
    messagingSenderId: '603417356334',
    projectId: 'prontomoto-d4547',
    storageBucket: 'prontomoto-d4547.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwdRxddKIREq64NSuXTEbbwguGOzQqwNo',
    appId: '1:603417356334:ios:c015dcf5f1c993ed4397bf',
    messagingSenderId: '603417356334',
    projectId: 'prontomoto-d4547',
    storageBucket: 'prontomoto-d4547.firebasestorage.app',
    iosBundleId: 'com.example.prontomotoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwdRxddKIREq64NSuXTEbbwguGOzQqwNo',
    appId: '1:603417356334:ios:c015dcf5f1c993ed4397bf',
    messagingSenderId: '603417356334',
    projectId: 'prontomoto-d4547',
    storageBucket: 'prontomoto-d4547.firebasestorage.app',
    iosBundleId: 'com.example.prontomotoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0FHAC8dkni2iizrRrqoenjN5Z0fTE77g',
    appId: '1:603417356334:web:20eca0280666a9a84397bf',
    messagingSenderId: '603417356334',
    projectId: 'prontomoto-d4547',
    authDomain: 'prontomoto-d4547.firebaseapp.com',
    storageBucket: 'prontomoto-d4547.firebasestorage.app',
    measurementId: 'G-Z3MSPJFTGS',
  );
}
